### PR TITLE
Moves from RuntimeStringInterpolator to MacroInterpolator.

### PR DESCRIPTION
**Pull request by FPerezP**
This change allows throwing discrepancy errors between queries and model at compile time instead of runtime.

It additionally splits the application into two different SBT modules, one for the examples and one
for the models.
We are doing it to avoid issues with macro expansion, which is additionally defining a new macro
(specifically the contextual macro interpolator), so we need them in different compilation units to
make it visible to the application code.

### CODE REVIEW

**Comment by FPerezP** [comment]
This PR fixes https://github.com/frees-io/freestyle-cassandra/issues/95

**Review by fedefernandez — APPROVED** [review]
This looks good to me.

**Comment by FPerezP** [comment]
@raulraja we’d like to know your thoughts on this since it's a little bit weird for us to be forced to have our annotated trait in a different sbt module. Defining the annotated trait in the same compilation unit makes this fail.  Is it ok with you to merge and go ahead with this behavior?
Here there is some more info about the issues Contextual has about this specific issue we are facing:

- https://github.com/propensive/contextual/issues/4
- https://github.com/propensive/contextual/pull/31

**Comment by raulraja** [comment]
It is indeed weird but I think this is a general issue with macros. I think this approach is fine and defining them in a different compilation unit if the user wants to guarantee compile time safety is a fair trade off. We just need to make sure we document this accordingly and explain the reasons why those need to be in separate compilation units. Maybe @propensive has some thoughts as to how he plans to solve these issues in contextual.

**Review by raulraja — APPROVED** [review]

**Comment by propensive** [comment]
I think that's exactly the compromise. Any code which gets run at compile time (i.e. the code which checks the interpolated string) *must* be compiled in an earlier phase. I'd be interested in any feedback on how to improve the user experience, in case any of this came as a surprise (or a misleading error) when you tried it!

**Pull request merged**
